### ISSUE TITLE
Access Control Feature Using Access Key: Secret Key:

### ISSUE THREAD

**Issue by null2noble** [storj-archived/tardigrade.io#137]
Like other object storage providers (AWS S3, Azure Blob, DO Spaces). They provide Access Key: Secret Key:
for easy access control of their storage. from anywhere you want to mount. When did this feature will be available in the tardigrade, Not using uplink CLI or gateway because it expires after exiting from it

**Comment by jtolio** [comment]
The right place to open this ticket is github.com/storj/storj, as this is our website repo.

Ultimately, I would like to understand more what you mean here. Tardigrade uses what we call an "access grant" which is an envelope containing a Macaroon-based bearer token combined with hierarchically derived end-to-end encryption keys. Access Grants are quite flexible, especially for easy access control of your storage, from anywhere you want to mount.

What makes you say you aren't using the uplink CLI or gateway because it expires after exiting from it?
